# Generated by Django 4.1.5 on 2023-01-25 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('no_of_items', models.IntegerField()),
                ('delivery_agent', models.CharField(max_length=100)),
                ('delivery_location', models.CharField(max_length=1000)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('in_transit', 'in_transit')], default='payment_pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'cash_on_delivery'), ('UPI', 'UPI')], max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
