# Generated by Django 4.1.5 on 2023-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryDetailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetail',
            name='delivery_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
