# Generated by Django 4.1.5 on 2023-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscart',
            name='status',
            field=models.CharField(choices=[('order_confirmed', 'order_confirmed'), ('in_cart', 'in_cart')], default='in_cart', max_length=20),
        ),
    ]
