# Generated by Django 4.1.5 on 2023-01-24 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantListingApp', '0002_alter_restaurants_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('dish', models.CharField(max_length=158)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=158, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantListingApp.restaurants')),
            ],
        ),
    ]
