# Generated by Django 4.1.5 on 2023-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
