# Generated by Django 4.1.5 on 2023-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=158)),
                ('location', models.CharField(max_length=500)),
                ('rating', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
