# Generated by Django 4.1.5 on 2023-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantListingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
